jobs:
- job: ${{ parameters.name }}
  pool: 
    vmImage: ${{ parameters.vmImage }}
  ${{ if or(eq(parameters.name, 'Alpine'), eq(parameters.name, 'CentOS7')) }}:
    container: ${{ parameters.container }}
  strategy:
    matrix:
      node_14_x:
        node_version: 14.x
        publish_artifacts: false
      node_16_x:
        node_version: 16.x
        publish_artifacts: true
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'

  # Install Watchman
  - ${{ if or(eq('macOS-latest', parameters.vmImage), eq('macos-11', parameters.vmImage)) }}:
    - script: |
        # https://github.com/actions/setup-python/issues/577
        rm /usr/local/bin/2to3 || true
        rm /usr/local/bin/idle3 || true
        rm /usr/local/bin/pydoc3 || true
        rm /usr/local/bin/python3 || true
        rm /usr/local/bin/python3-config || true
        brew update
        brew install watchman
      displayName: Install Watchman

  - ${{ if eq(parameters.name, 'Windows') }}:
    - script: |
        cp -rf $(System.DefaultWorkingDirectory)\watchman $(Agent.HomeDirectory)
      displayName: Copy Watchman
    - script: |
        set PATH=%PATH%;$(Agent.HomeDirectory)\watchman\windows\bin
        echo "##vso[task.setvariable variable=PATH]%PATH%"
        watchman -v
      displayName: Install Watchman

  - script: npm install --build-from-source
    displayName: Install dependencies
  - script: npm test
    displayName: Run tests
  - script: yarn prebuild --arch=${{ parameters.arch }}
    displayName: Test prebuild

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    condition: and(succeeded(), eq(variables['publish_artifacts'], 'true'))
    inputs:
      artifactName: prebuilds
      pathtoPublish: '$(System.DefaultWorkingDirectory)/prebuilds'
